---
language: python
services: docker


env:
  global:
    - ROLE_NAME: jitsi-meet-focal
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    # - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: debian10



# Install ansible
addons:
  apt:
    packages:
    - python3-pip

install:
  - pip3 install molecule yamllint ansible-lint docker ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME c-goes.$ROLE_NAME
  - cd c-goes.$ROLE_NAME

script:
  - molecule test --scenario-name docker

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/