- name: only accept supported auth types
  assert:
    that:
        - meet_auth_type in ['ldap', 'ldap2', 'internal_hashed', 'anonymous', 'jwt']



- name: run tasks for jwt-authentication
  include: auth_jwt.yml
  when: meet_auth_type and meet_auth_type == "jwt"




- name: run tasks for non-jwt authentication
  include: auth_other.yml
  when: meet_auth_type != "jwt"