---

- lineinfile:
    path: /etc/prosody/prosody.cfg.lua
    line: consider_bosh_secure = true
    insertbefore: "^Include"
  notify:
    - restart prosody

- name: install ldap packages
  apt:
    name:
      - prosody-modules
      - lua-ldap


- name: configure prosody for ldap
  copy:
    dest: /etc/prosody/conf.avail/ldap.cfg.lua
    content: |
      -- https://modules.prosody.im/mod_lib_ldap.html
      -- https://modules.prosody.im/mod_auth_ldap2.html
      authentication = 'ldap2'
      
      ldap = {
          hostname = '{{ meet_ldap_host }}',
          bind_dn = '{{ meet_ldap_binddn }}',
          bind_password = '{{ meet_ldap_bindpw }}',
          use_tls = {{ 'true' if meet_ldap_check_peer else 'false' }},
          user = {
              usernamefield = 'uid',
              basedn = '{{ meet_ldap_base }}',
              filter = '(objectClass=*)',
        -- admin?
              --namefield = 'cn',
          },
      }
  notify:
    - restart prosody


- name: link ldap conf
  file:
    path: /etc/prosody/conf.d/ldap.cfg.lua
    src: /etc/prosody/conf.avail/ldap.cfg.lua
    state: link
  notify:
    - restart prosody

  
- name: configure ldap.conf
  lineinfile:
    path: /etc/ldap/ldap.conf
    line: TLS_REQCERT never
    insertbefore: EOF
  notify:
    - restart prosody
