---


- name: saslauthd absent when using ldap2
  apt:
    name:
      - sasl2-bin
      - libsasl2-modules-ldap
      - lua-cyrussasl
    state: absent

- name: consider bosh secure for prosody
  lineinfile:
    path: /etc/prosody/prosody.cfg.lua
    line: consider_bosh_secure = true
    insertbefore: "^Include"
  notify:
    - restart prosody

- name: install ldap packages
  apt:
    name:
      - prosody-modules
      - lua-ldap


- name: enable access for guests in prosody
  blockinfile:
    path: /etc/prosody/conf.d/{{ meet_domain }}.cfg.lua
    marker: "-- {mark} ANSIBLE MANAGED BLOCK for ldap2 config (prosody)"
    block: |
      ldap = {
        hostname = '{{ meet_ldap_host }}',
        bind_dn = '{{ meet_ldap_binddn }}',
        bind_password = '{{ meet_ldap_bindpw }}',
        use_tls = {{ 'true' if meet_ldap_use_tls else 'false' }},
        user = {
            usernamefield = 'uid',
            basedn = '{{ meet_ldap_base }}',
            filter = '(objectClass=*)',
        },
      }
    insertafter: '^[\s]*authentication = "ldap2"'
    state: present
  notify:
    - restart prosody


- name: configure ldap.conf
  lineinfile:
    path: /etc/ldap/ldap.conf
    line: TLS_REQCERT never
    insertbefore: EOF
  notify:
    - restart prosody
