- name: configure own stun server for p2p connections
  lineinfile:
    path: /etc/jitsi/meet/{{ meet_domain }}-config.js
    regexp: '^[ ]*{ urls: '
    line: "            { urls: 'stun:{{ meet_domain }}:443' }"
  notify:
      - restart nginx

- name: configure videobridge sip-communicator for stun
  lineinfile:
    path: /etc/jitsi/videobridge/sip-communicator.properties
    regexp: "^org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES="
    line: org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES={{ meet_domain }}:443
  notify:
      - restart jitsi-videobridge2
  