- name: Change jitsi-videobridge2 memory
  lineinfile:
    line: "VIDEOBRIDGE_MAX_MEMORY={{ meet_videobridge_memory }}"
    regexp: "^VIDEOBRIDGE_MAX_MEMORY=.*"
    path: /etc/jitsi/videobridge/config
  notify:
    - restart jitsi-videobridge2
  tags:
    - videobridge

- name: cron to restart Vidobridge nightly
  cron:
    name: restart jitsi-videobridge2
    hour: "4"
    #minute: "{{ 60 |random(seed=inventory_hostname) }}"
    minute: "33"
    user: root
    job: "/usr/sbin/service jitsi-videobridge2 restart  >> /var/log/jitsi/restart_videobridge2.log 2>&1"
    cron_file: restart_jitsi-videobridge
  when: meet_jvb_nightly_restart
  tags:
    - videobridge
