---
- name: Converge
  hosts: all
  become: true
  vars:
    meet_snakeoil_cert: yes
    meet_domain: meet.test
    meet_logo_url: ''
    meet_auth_type: anonymous
    molecule: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install test dependencies (RedHat).
      package: name=which state=present
      when: ansible_os_family == 'RedHat'

    - name: Install test dependencies.
      package: name=curl state=present

  roles:
    - role: c-goes.jitsi-meet-focal

