---
- name: Converge
  hosts: all
  vars:
    meet_snakeoil_cert: yes
    meet_domain: meet.test
    meet_logo_url: ''
    meet_auth_type: anonymous
    molecule: yes
  tasks:
    - name: "Include jitsi-meet-focal"
      include_role:
        name: "jitsi-meet-focal"
