---
dependency:
  name: galaxy
driver:
  name: podman
platforms:

  # echo 0 | sudo tee /proc/sys/net/ipv4/ip_unprivileged_port_start


  - name: instance
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true # true: ansible is installed in image

    published_ports:
      - 0.0.0.0:443:443/tcp # nginx
      - 0.0.0.0:10000:10000/udp # ??
      # stun/turn port TODO

    command: /sbin/init
    tty: True

    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro



provisioner:
  name: ansible
verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8